site_name: SPDX v3 Specification
site_description: The System Package Data Exchange (SPDX) Specification Version 3.0
site_author: Linux Foundation and its Contributors
site_url: https://spdx.github.io/spdx-spec/  # set to the "root" of the site, to be combined with canonical_version
repo_url: https://github.com/spdx/spdx-spec/
edit_uri: ""  # set to an empty string to disable edit links; to enable, set to blob/development/v3.0.1/docs/
copyright: SPDX v3.0 Copyright © 2010-2024 Linux Foundation and its Contributors.
use_directory_urls: true
theme: readthedocs
plugins:
- search
- mike:
    canonical_version: latest  # tell search engines to prefer the latest version
    alias_type: redirect  # use redirect so the URL in the browser changes
- pdf-export:
    combined: true
    media_type: print
    enabled_if_env: ENABLE_PDF_EXPORT  # only export PDF if this is set to 1
extra_css:
- css/style.css
markdown_extensions:
- codehilite:
    guess_lang: false
strict: true
validation:
  nav:
    omitted_files: info  # allow during development where there are moving parts
    not_found: info      # allow during development where there are moving parts
    absolute_links: warn
  links:
    not_found: warn
    anchors: warn
    absolute_links: warn
    unrecognized_links: warn
nav:
- 'Copyright': index.md
- 'Introduction': introduction.md
- 'Scope': scope.md
- 'Normative references': normative-references.md
- 'Terms and definitions': terms-and-definitions.md
- 'Model and serializations': serializations.md
- 'Bibliography': bibliography.md
- model  # __MODEL_PLACEHOLDER__, to be replaced by content from mkdocs-files.yml
- annexes:
  - 'Diffs from Previous Editions': annexes/diffs-from-previous-editions.md
  - 'Getting started with SPDX 3': annexes/getting-started.md
  - 'RDF Object Model and Identifier Syntax': annexes/RDF-object-model-and-identifier-syntax.md
  - 'SPDX License Expressions': annexes/SPDX-license-expressions.md
  - 'Using SPDX short identifiers in Source Files': annexes/using-SPDX-short-identifiers-in-source-files.md
  - 'Using SPDX to comply with norms, standards and regulation': annexes/using-SPDX-to-comply-with-industry-guidance.md
  - 'Including Security Information in SPDX': annexes/including-security-information-in-SPDX.md
  - 'SPDX Lite': annexes/SPDX-Lite.md
- licenses:
  - 'Creative Commons Attribution License 3.0 Unported': licenses/CC-BY-3.0.md
  - 'Community Specification License 1.0': licenses/Community-Spec-1.0.md
