site_name: SPDX v3 Specification
site_description: The System Package Data Exchange (SPDX) Specification Version 3.0.1 - Open standard for creating Software Bills of Materials (SBOMs)
site_author: The Linux Foundation and its Contributors, including SPDX Model contributions from OMG and its Contributors.
site_url: https://spdx.github.io/spdx-spec/  # set to the "root" of the site, to be combined with canonical_version
repo_url: https://github.com/spdx/spdx-spec/
edit_uri: ""  # set to an empty string to disable edit links; to enable, set to blob/development/v3.0.1/docs/
copyright: SPDX v3.0.1 Copyright © 2010-2024, The Linux Foundation and its Contributors, including SPDX Model contributions from OMG and its Contributors.
use_directory_urls: true
theme:
  name: readthedocs
  sticky_navigation: true
plugins:
- search
- mike:
    canonical_version: v3.0.1
    alias_type: redirect  # use redirect so the URL in the browser changes
- pdf-export:
    combined: true
    media_type: print
    enabled_if_env: ENABLE_PDF_EXPORT  # only export PDF if this is set to 1
extra_css:
- css/style.css
markdown_extensions:
- codehilite:
    guess_lang: false
strict: true
validation:
  nav:
    omitted_files: warn  
    not_found: info       # model will not exist for PR validation
    absolute_links: warn
  links:
    not_found: warn
    anchors: warn
    absolute_links: warn
    unrecognized_links: warn
nav:
- 'Copyright': index.md
- 'Introduction': introduction.md
- '1. Scope': scope.md
- '2. References': references.md
- '3. Symbols': symbols.md
- '4. Conformance': conformance.md
- '5. Model and serializations': serializations.md
- model:  # [MODEL_PLACEHOLDER], to be replaced by content from mkdocs-files.yml
- annexes:
  - 'A. Changes from the previous standard': annexes/diffs-from-previous-iso.md
  - 'B. RDF model definition and diagrams': annexes/rdf-model.md
  - 'C. SPDX license expressions': annexes/SPDX-license-expressions.md
  - 'D. SPDX license list matching guidelines': annexes/license-matching-guidelines-and-templates.md
  - 'E. SPDX Lite': annexes/SPDX-Lite.md
  - 'F. Package URL specification': annexes/pkg-url-specification.md
- licenses:
  - 'Community Specification License 1.0': licenses/Community-Spec-1.0.md
  - 'Creative Commons Attribution License 3.0 Unported': licenses/CC-BY-3.0.md
draft_docs: |  # for preview with `mkdocs serve`, but excluded from `mkdocs build`
  omg-preface.md
  iso-foreword.md
  conformance.md
