site_name: SPDX Specification 3.0.1
site_description: The System Package Data Exchange (SPDX) Specification Version 3.0.1 - Open standard for creating Software Bills of Materials (SBOMs)
site_author: The Linux Foundation and its Contributors, including SPDX Model contributions from OMG and its Contributors.
site_url: https://spdx.github.io/spdx-spec/  # set to the "root" of the site, to be combined with canonical_version
repo_url: https://github.com/spdx/spdx-spec/
edit_uri: ""  # set to an empty string to disable edit links; to enable, set to blob/development/v3.0.1/docs/
copyright: SPDX v3.0.1 Copyright © 2010-2024, The Linux Foundation and its Contributors, including SPDX Model contributions from OMG and its Contributors.
use_directory_urls: true
theme:
  name: readthedocs
  sticky_navigation: true
plugins:
- search
- mike:
    canonical_version: v3.0.1  # tell search engines to prefer the URL of v3.0.1
    alias_type: redirect  # use redirect so it can redirect every pages (not just the root of the version)
- pdf-export:
    combined: true
    media_type: print
    enabled_if_env: ENABLE_PDF_EXPORT  # only export PDF if this is set to 1
extra_css:
- css/style.css
markdown_extensions:
- codehilite:
    guess_lang: false
strict: true
validation:
  nav:
    omitted_files: warn  # use "info" to relax during development where there are moving parts
    not_found: warn      # warn if a file is referenced in the nav but not included in the build
    absolute_links: warn
  links:
    not_found: warn
    anchors: warn
    absolute_links: warn
    unrecognized_links: warn
nav:
- 'Copyright': index.md
- 'Foreword': iso-foreword.md
- 'Preface': omg-preface.md
- 'Introduction': introduction.md
- '1. Scope': scope.md
- '2. References': references.md
- '3. Symbols': symbols.md
- '4. Terms and definitions': terms-and-definitions.md
- '5. Conformance': conformance.md
- '6. Model and serializations': serializations.md
- 'Test - OMG Preface': omg-preface.md
- 'Test - ISO Foreword': iso-foreword.md
- model:  # __MODEL_PLACEHOLDER__, to be replaced by content from mkdocs-files.yml
  - "__MODEL_PLACEHOLDER__": "https://example.com"
- annexes:
  - 'A. Changes from the previous standard': annexes/changes-from-previous-iso.md
  - 'B. RDF model definition and diagrams': annexes/rdf-model.md
  - 'C. SPDX license expressions': annexes/spdx-license-expressions.md
  - 'D. SPDX License List matching guidelines': annexes/license-matching-guidelines-and-templates.md
  - 'E. SPDX Lite': annexes/spdx-lite.md
  - 'F. Package URL specification': annexes/pkg-url-specification.md
  - 'G. History with OMG': omg-history.md
- licenses:
  - 'Community Specification License 1.0': licenses/Community-Spec-1.0.md
  - 'Creative Commons Attribution License 3.0 Unported': licenses/CC-BY-3.0.md
#draft_docs: |  # for preview with `mkdocs serve`, but excluded from `mkdocs build`
#  omg-preface.md
#  iso-foreword.md
