site_name: SPDX v3 Specification
site_description: The System Package Data Exchange (SPDX) - Open standard for creating Software Bills of Materials (SBOMs), managing software components, enhancing supply chain security, and streamlining compliance.
site_author: Linux Foundation and its Contributors
site_url: https://spdx.github.io/spdx-spec/  # set to the "root" of the site, to be combined with canonical_version
repo_url: https://github.com/spdx/spdx-spec/
edit_uri: ""  # set to an empty string to disable edit links; to enable, set to blob/development/v3.0.1/docs/
copyright: -- DRAFT -- SPDX v3.0.1 Copyright © 2010-2024 Linux Foundation and its Contributors. -- DRAFT -- This is a test website. Do not use this. Official SPDX specification is at <a href="http://spdx.org/specifications">http://spdx.org/specifications</a>.
use_directory_urls: true
theme:
  name: readthedocs
  sticky_navigation: true
plugins:
- search
- mike:
    canonical_version: v3.0.1  # tell search engines to prefer v3.0.1 version
    alias_type: redirect  # use redirects so the URL in the browser changes
- pdf-export:
    combined: true
    media_type: print
    enabled_if_env: ENABLE_PDF_EXPORT  # only export PDF if this is set to 1
extra_css:
- css/style.css
markdown_extensions:
- codehilite:
    guess_lang: false
strict: true
validation:
  nav:
    omitted_files: warn
    not_found: info      # allow during development where there are moving parts
    absolute_links: warn
  links:
    not_found: warn
    anchors: warn
    absolute_links: warn
    unrecognized_links: warn
nav:
- 'Copyright': index.md
- 'Introduction': introduction.md
- 'Scope': scope.md
- 'Normative references': normative-references.md
- 'Terms and definitions': terms-and-definitions.md
- 'Model and serializations': serializations.md
- 'Bibliography': bibliography.md
- model  # __MODEL_PLACEHOLDER__, to be replaced by content from mkdocs-files.yml
- annexes:
  - 'Differences from previous editions': annexes/diffs-from-previous-editions.md
  - 'Getting started with SPDX 3': annexes/getting-started.md
  - 'RDF object model and identifier syntax': annexes/RDF-object-model-and-identifier-syntax.md
  - 'SPDX license expressions': annexes/SPDX-license-expressions.md
  - 'License matching guidelines and templates': annexes/license-matching-guidelines-and-templates.md
  - 'Using SPDX license list short identifiers in source files': annexes/using-SPDX-short-identifiers-in-source-files.md
  - 'Using SPDX to comply with norms, standards and regulation': annexes/using-SPDX-to-comply-with-industry-guidance.md
  - 'Including security information in a SPDX document': annexes/including-security-information-in-SPDX.md
  - 'SPDX Lite': annexes/SPDX-Lite.md
  - 'Cross referencing in SPDX 3': annexes/cross-reference.md
  - 'Package URL specification v1': annexes/pkg-url-specification.md
- licenses:
  - 'Creative Commons Attribution License 3.0 Unported': licenses/CC-BY-3.0.md
  - 'Community Specification License 1.0': licenses/Community-Spec-1.0.md
draft_docs: |  # for preview with `mkdocs serve`, but excluded from `mkdocs build`
  ISO_foreword.md
  conformance.md
