on:
  push:
    branches:
      - development/v3.0
  repository_dispatch:
    types:
      - publish_v3_spec
  workflow_dispatch: {}
jobs:
  build:
    runs-on: ubuntu-latest
    container: python:3
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332  #v4.1.7
        with:
          ref: development/v3.0
          path: spdx-spec
          fetch-depth: 0  # Because we will be pushing the gh-pages branch
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332  #v4.1.7
        with:
          repository: spdx/spec-parser
          ref: main
          path: spec-parser
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332  #v4.1.7
        with:
          repository: spdx/spdx-3-model
          ref: v3.0  # Use the v3.0 tag release
          path: spdx-3-model
      - name: Install pre-requisites
        run: pip install -r spdx-spec/requirements.txt
      - name: Install pre-requisites for spec-parser
        run: pip install -r spec-parser/requirements.txt
      - name: Build model
        run: python3 spec-parser/main.py spdx-3-model/model spdx-spec/docs/model
      - name: Copy JSON annotations
        run: cp spdx-spec/serialization/jsonld/annotations.ttl spdx-spec/docs/model/jsonld-annotations.ttl
      - name: Generate JSON schema
        run: |
          shacl2code generate \
            --input spdx-spec/docs/model/spdx-model.ttl \
            --input spdx-spec/docs/model/jsonld-annotations.ttl \
            --context-url spdx-spec/docs/model/spdx-context.jsonld https://spdx.org/rdf/3.0.0/spdx-context.jsonld \
            jsonschema \
            --output spdx-spec/docs/model/schema.json
      - name: Set Git identity
        working-directory: spdx-spec
        run: git config user.name ci-bot; git config user.email ci-bot@spdx.dev
      - name: Sync gh-pages
        working-directory: spdx-spec
        run: git checkout gh-pages && git pull && git checkout development/v3.0
      - name: Deploy the v3.0 site and set aliases (v3.0-RC1, v3.0-RC2, v3.0.0)
        working-directory: spdx-spec
        run: |
          MODEL_YML="docs/model/mkdocs-files.yml"
          BASE_MKDOCS_YML="mkdocs.yml"
          FULL_MKDOCS_YML="__mkdocs-full.yml"
          echo "Build $FULL_MKDOCS_YML from $BASE_MKDOCS_YML and $MODEL_YML"
          sed -e "\|- model.*#.*__MODEL_PLACEHOLDER__.*|{
              r $MODEL_YML
              a\\

              d
          }" "$BASE_MKDOCS_YML" > "$FULL_MKDOCS_YML"
          echo "====================="
          echo "Deploy using $FULL_MKDOCS_YML"
          echo "====================="
          mike deploy --update-aliase --config-file "$FULL_MKDOCS_YML" --branch gh-pages --push v3.0 v3.0-RC1 v3.0-RC2 v3.0.0
