on:
  pull_request:
    paths:
      - 'examples/**/*.json'
      - 'docs/annexes/*.md'
  push:
    paths:
      - 'examples/**/*.json'
      - 'docs/annexes/*.md'

jobs:
  validate-examples:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871  #v4.2.1
      - name: Install Python dependencies
        run: |
          python3 -m pip install check-jsonschema==0.29.3 pyshacl==0.26.0
      - name: Install dependencies
        run: |
          sudo apt install -y gawk

      - name: Check examples
        run: |
          ./bin/check-examples.sh
